server:
  port: 8081
spring:
  application:
    name: publisher
  activemq:
    broker-url: tcp://172.23.55.167:61616
    user: admin
    password: admin

demo:
  my:
    request:
      queue: demo.my.request.queue