server:
  port: 8080

spring:
  activemq:
    broker-url: tcp://172.23.55.167:61616
    user: admin
    password: admin

logging:
  level:
    springbootjms:
      com:
        epam:
          activemq:
            jms:
              impl: INFO

activemq:
  queue: simple-queue
  topic: simple-topic